---
  - name: Update apt cache if needed
    apt: update_cache=yes cache_valid_time=3600 autoremove=yes

  - name: Install needed packages for the app
    apt: pkg={{item}} state=installed autoremove=yes
    with_items:
      - software-properties-common
      - mysql-client
      - build-essential
      - nginx

  - name: copy nginx config file
    copy: src=files/nginx.conf dest=/etc/nginx/sites-available/default

  - name: enable configuration
    file: src=/etc/nginx/sites-available/default dest=/etc/nginx/sites-enabled/default state=link

  - name: copy index.html
    template: src=templates/index.html dest=/usr/share/nginx/html/index.html mode=0644
